---
# Specify users which will be able to access docker without root privileges
docker_users:
  - "{{ ansible_user }}"

# Restart policy for Docker containers
docker_restart_policy: "always"

project_name: "hl-demo"

fabric_starter_workdir: "/home/{{ ansible_user }}/{{ project_name }}"
docker_artifacts: "{{ fabric_starter_workdir }}/dockercompose"
fabric_artifacts: "{{ fabric_starter_workdir }}/artifacts"

# Use couchdb in peers instead of leveldb
#use_couchdb: 'yes'
use_couchdb: 'no'
couchdb_port: 5984

# Hyperledger framework version
fabric_version: "1.4.4"
fabric_pack: "{{ fabric_version }}"
# fabric_thirdparty_version needed for couchdb, kafka etc..
fabric_thirdparty_version: "0.4.15"
fabric_rest_version: "latest"
node_version: "8-alpine"

# Hyperledger explorer configs
hl_explorer_version: 1.1.4
hl_explorer_port: 8080
hl_explorer_username: "admin"
hl_explorer_password: "adminpw"

# Default HL fabric ports
orderer_port: 7050
api_port: 4000
ca_port: 7054
peer0_port: 7051

#Chaincode configs
chaincode: "{{ fabric_starter_workdir }}/chaincode"

# Define private collections configuration
collections_config_param: ""
collections_config_name: ""
collections_config_path: ""

#collections_config_param: "--collections_config"
#collections_config_name: "collections_config.json"
#collections_config_path: "{{ chaincode }}/{{ chaincode_lang }}/{{ chaincode_common_name }}/{{ collections_config_name }}"

# Folders to create for configs
fabric_artifacts_folders:
  - "{{ fabric_starter_workdir }}"
  - "{{ docker_artifacts }}"
  - "{{ fabric_artifacts }}"
  - "{{ fabric_artifacts }}/channel"
  - "{{ fabric_artifacts }}/connection-profile"
  - "{{ chaincode }}"
  - "{{ fabric_starter_workdir }}/www-client"

# Configuration files to transfer list
# - source
#   destination

fabric_templates:
  - from: "docker-compose-templates/base.yaml"
    to: "{{ docker_artifacts }}/base.yaml"
  - from: "artifact-templates/configtxtemplate.yaml"
    to: "{{ fabric_artifacts }}/configtx.yaml"
  - from: "artifact-templates/network-config-template.json"
    to: "{{ fabric_artifacts }}/network-config.json"

peer_templates:
  - from: "artifact-templates/fabric-ca-server-configtemplate.yaml"
    to: "{{ fabric_artifacts }}/fabric-ca-server-{{ org }}.yaml"
  - from: "docker-compose-templates/docker-composetemplate-peer.yaml"
    to: "{{ docker_artifacts }}/docker-compose-{{ org }}.yaml"
  - from: "artifact-templates/cryptogentemplate-peer.yaml"
    to: "{{ fabric_artifacts }}/cryptogen-{{ org }}.yaml"

orderer_templates:
  - from: "docker-compose-templates/docker-composetemplate-orderer.yaml"
    to: "{{ docker_artifacts }}/docker-compose-{{ global_domain }}.yaml"
  - from: "artifact-templates/cryptogentemplate-orderer.yaml"
    to: "{{ fabric_artifacts }}/cryptogen-{{ global_domain }}.yaml"

files_to_rsync_orderer:
  - from: "{{ org }}Config.json"
    to: ""
  - from: "crypto-config/peerOrganizations/{{ org }}.{{ global_domain }}/msp"
    to: "crypto-config/peerOrganizations/{{ org }}.{{ global_domain }}"
  - from: "crypto-config/peerOrganizations/{{ org }}.{{ global_domain }}/peers/peer0.{{ org }}.{{ global_domain }}/tls/ca.crt"
    to: "crypto-config/peerOrganizations/{{ org }}.{{ global_domain }}/peers/peer0.{{ org }}.{{ global_domain }}/tls"
  - from: "crypto-config/peerOrganizations/{{ org }}.{{ global_domain }}/peers/peer0.{{ org }}.{{ global_domain }}/msp/tlscacerts/tlsca.{{ org }}.{{ global_domain }}-cert.pem"
    to: "crypto-config/peerOrganizations/{{ org }}.{{ global_domain }}/peers/peer0.{{ org }}.{{ global_domain }}/msp/tlscacerts"
#  - from: "crypto-config/peerOrganizations/{{ org }}.{{ global_domain }}/peers/peer1.{{ org }}.{{ global_domain }}/tls/ca.crt"
#    to: "crypto-config/peerOrganizations/{{ org }}.{{ global_domain }}/peers/peer1.{{ org }}.{{ global_domain }}/tls"

files_to_rsync_nodes_phase1:
  - from: "crypto-config/ordererOrganizations/{{ global_domain }}/orderers"
    to: "crypto-config/ordererOrganizations/{{ global_domain }}"
  - from: "crypto-config/ordererOrganizations/{{ global_domain }}/tlsca/tlsca.{{ global_domain }}-cert.pem"
    to: "crypto-config/ordererOrganizations/{{ global_domain }}/tlsca"
  - from: "channel"
    to: ""
files_to_rsync_nodes_phase2:
  - from: "*.block"
    to: ""

files_hl_explorer:
  - from: "artifact-templates/explorer-config.json"
    to: "{{ fabric_artifacts }}/explorer-config.json"
  - from: "artifact-templates/connection-profile/test-network.json"
    to: "{{ fabric_artifacts }}/connection-profile/test-network.json"
  - from: "docker-compose-templates/docker-composetemplate-explorer.yaml"
    to: "{{ docker_artifacts }}/docker-compose-explorer.yaml"
