---
fabric_version: "1.2.0"
fabric_pack: "amd64-{{ fabric_version }}"
node_version: "8-alpine"
fabric_thirdparty_version: "0.4.14"
#nginx_version:
#fabric_baseos_version:
#fabric_rest_version:

fabric_docker_images:
  - image: "hyperledger/fabric-ca"
    version: "{{ fabric_pack }}"
  - image: "hyperledger/fabric-orderer"
    version: "{{ fabric_pack }}"
  - image: "hyperledger/fabric-peer"
    version: "{{ fabric_pack }}"
  - image: "hyperledger/fabric-ccenv"
    version: "{{ fabric_pack }}"
  - image: "hyperledger/fabric-tools"
    version: "{{ fabric_pack }}"
  - image: "hyperledger/fabric-baseos"
    version: "{{ fabric_thirdparty_version | default('latest') }}"
  - image: "dockeraltoros/fabric-rest"
    version: "{{ fabric_rest_version | default('latest') }}"
  - image: "nginx"
    version: "{{ nginx_version | default('latest') }}"
  - image: "node"
    version: "{{ node_version | default('latest') }}"

kafka_docker_images:
  - image: hyperledger/fabric-kafka
    version: "{{ fabric_thirdparty_version }}"
  - image: hyperledger/fabric-zookeeper
    version: "{{ fabric_thirdparty_version }}"